#!/bin/sh

if [ -z "`git config --local user.name`" ]; then
    echo "fatal: user.name is not set local"
    exit 1
fi
if [ -z "`git config --local user.email`" ]; then
    echo "fatal: user.email is not set local"
    exit 1
fi
